apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartx-ledger
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smartx-ledger
  template:
    metadata:
      labels:
        app: smartx-ledger
    spec:
      containers:
        - name: smartx-ledger
          image: docker.io/pb26457093/smartx-ledger:9
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: smartx-ledger-config
            - secretRef:
                name: smartx-ledger-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
