apiVersion: v1
kind: Service
metadata:
  name: hamsa-ledger
  labels:
    app: hamsa-ledger
spec:
  type: ClusterIP
  selector:
    app: hamsa-ledger
  ports:
    - name: http
      port: 8080
      targetPort: 8080
