apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartx-ledger
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: smartx-ledger
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
